# Graph database constants

NODE_REQUIREMENT = "Requirement"
NODE_ABSENCE = "Absence"
NODE_UI_ELEMENT = "UIElement"
NODE_USER_FLOW = "UserFlow"
NODE_CODE_FILE = "CodeFile"
NODE_CODE_FUNCTION = "CodeFunction"

EDGE_COVERS = "COVERS"
EDGE_HAS_ABSENCE = "HAS_ABSENCE"
EDGE_PART_OF = "PART_OF"
EDGE_IMPLEMENTS = "IMPLEMENTS"
EDGE_CALLS = "CALLS"
EDGE_DEFINED_IN = "DEFINED_IN"
EDGE_TRANSITION = "TRANSITION"
